// Fragen-Sammlung für die Fragerunde.
// Jeder Eintrag: { text, category }
// Kategorien werden automatisch zu Filter-Chips auf /fragen.

window.QUESTIONS = [

  // ---------- Über dich (25) ----------
  { text: "Würdest du deine schönste Erinnerung hergeben, damit du deine schlimmste auslöschen kannst?", category: "Über dich" },
  { text: "Was würdest du an deinem Körper gerne verändern?", category: "Über dich" },
  { text: "Was versuchst du vor anderen Menschen zu verbergen?", category: "Über dich" },
  { text: "Was möchtest du gewesen sein?", category: "Über dich" },
  { text: "Wovor hast du am meisten Angst?", category: "Über dich" },
  { text: "Für welche Eigenschaften an dir hast du am öftesten Komplimente bekommen?", category: "Über dich" },
  { text: "Was denken andere über dich, das überhaupt nicht stimmt?", category: "Über dich" },
  { text: "Gibt es ein Gefühl, das du selten zulässt — und wovor hättest du Angst, wenn du es doch zuließest?", category: "Über dich" },
  { text: "Welche Rolle spielst du in Gruppen, ohne dass du sie bewusst gewählt hättest?", category: "Über dich" },
  { text: "Was an dir hat sich in den letzten fünf Jahren am meisten verändert?", category: "Über dich" },
  { text: "Worin bist du heimlich gut — etwas, das kaum jemand von dir weiß?", category: "Über dich" },
  { text: "Welchen Satz hast du dir selbst schon oft gesagt, aber noch nie wirklich geglaubt?", category: "Über dich" },
  { text: "Was bedeutet „zu Hause“ für dich — und wann hast du es zuletzt gespürt?", category: "Über dich" },
  { text: "Gibt es einen Teil von dir, den du erst in einer bestimmten Konstellation zeigst?", category: "Über dich" },
  { text: "Was tust du, wenn du dich unbeobachtet fühlst, was du nie jemandem erzählen würdest?", category: "Über dich" },
  { text: "Welcher deiner eigenen Sätze überrascht dich selbst immer wieder?", category: "Über dich" },
  { text: "Wann hast du zuletzt einen Moment gehabt, in dem du gedacht hast: „So bin ich wirklich“?", category: "Über dich" },
  { text: "Was an dir würdest du auf keinen Fall verändern?", category: "Über dich" },
  { text: "In welcher Situation bist du am meisten du selbst?", category: "Über dich" },
  { text: "Welchen Teil deiner Kindheit trägst du noch heute in dir?", category: "Über dich" },
  { text: "Vor welcher Wahrheit über dich selbst hast du am meisten Angst?", category: "Über dich" },
  { text: "Welches Kompliment hat dich nachhaltig geprägt?", category: "Über dich" },
  { text: "Worin unterscheidest du dich vom Rest deiner Familie?", category: "Über dich" },
  { text: "Was ist deine ehrliche Meinung zu dir selbst, wenn niemand zuhört?", category: "Über dich" },
  { text: "Worüber lachst du heimlich, obwohl du weißt, dass du es nicht solltest?", category: "Über dich" },

  // ---------- Werte & Richtung (25) ----------
  { text: "Glaubst du an Schicksal?", category: "Werte & Richtung" },
  { text: "Welche war die größte und bedeutendste Entscheidung, die du mal treffen musstest?", category: "Werte & Richtung" },
  { text: "Würdest du gerne wissen wollen wann du stirbst?", category: "Werte & Richtung" },
  { text: "Wenn du einem kleinen Kind einen Rat mitgeben könntest für den Rest seines Lebens — welcher wäre das?", category: "Werte & Richtung" },
  { text: "Gibst du dein Geld lieber für materielle Dinge oder für Erlebnisse aus?", category: "Werte & Richtung" },
  { text: "Was ist dein Lieblingszitat?", category: "Werte & Richtung" },
  { text: "Wärst du lieber weniger attraktiv und steinreich oder extrem gutaussehend, aber dafür arm?", category: "Werte & Richtung" },
  { text: "Wenn du nur noch einen Wert verteidigen dürftest — welcher wäre es?", category: "Werte & Richtung" },
  { text: "Was würdest du tun, wenn du wüsstest, du kannst nicht scheitern?", category: "Werte & Richtung" },
  { text: "Wann hast du zuletzt etwas getan, nur weil du es für richtig gehalten hast — nicht weil es klug war?", category: "Werte & Richtung" },
  { text: "Welche Regel, die du dir selbst gegeben hast, brichst du heimlich am häufigsten?", category: "Werte & Richtung" },
  { text: "Was hältst du für Luxus, was man nicht kaufen kann?", category: "Werte & Richtung" },
  { text: "Wofür würdest du alles stehen lassen und gehen?", category: "Werte & Richtung" },
  { text: "Welche Wahrheit kannst du nur schwer aussprechen, obwohl du weißt, sie wäre nötig?", category: "Werte & Richtung" },
  { text: "Was ist für dich der Unterschied zwischen „gut leben“ und „ehrlich leben“?", category: "Werte & Richtung" },
  { text: "Welchen Preis hast du für deine wichtigsten Entscheidungen bezahlt?", category: "Werte & Richtung" },
  { text: "Wenn du dein 20-jähriges Ich treffen könntest — welchen einen Satz würdest du sagen?", category: "Werte & Richtung" },
  { text: "Was ist für dich nicht verhandelbar?", category: "Werte & Richtung" },
  { text: "Wann hast du zuletzt bewusst die Kontrolle abgegeben — wie hat's sich angefühlt?", category: "Werte & Richtung" },
  { text: "Wofür hast du dich zuletzt geschämt — und warum eigentlich?", category: "Werte & Richtung" },
  { text: "Welche deiner Entscheidungen würdest du wieder genau so treffen, welche nicht?", category: "Werte & Richtung" },
  { text: "Was ist die wichtigste Lektion, die du aus einem Scheitern gelernt hast?", category: "Werte & Richtung" },
  { text: "Wann weißt du, dass etwas „genug“ ist?", category: "Werte & Richtung" },
  { text: "Was ist schwerer für dich: zu geben oder zu nehmen?", category: "Werte & Richtung" },
  { text: "Hat deine Definition von Erfolg sich verändert — wie?", category: "Werte & Richtung" },

  // ---------- Träume & Zukunft (15) ----------
  { text: "Welchen Beruf würdest du ausüben, wenn Geld keine Rolle spielen würde?", category: "Träume & Zukunft" },
  { text: "Welchen Traum wirst du dir, deiner Meinung nach, nie erfüllen können?", category: "Träume & Zukunft" },
  { text: "Was ist deine größte Fantasie?", category: "Träume & Zukunft" },
  { text: "Wie denkst du, sieht dein Leben in zehn Jahren aus?", category: "Träume & Zukunft" },
  { text: "Gibt es etwas, wovon du schon lange träumst, dich aber noch nicht getraut hast, es zu tun?", category: "Träume & Zukunft" },
  { text: "In fünf Jahren sitzt du wieder hier — was muss bis dahin passiert sein, damit du zufrieden bist?", category: "Träume & Zukunft" },
  { text: "Wenn du ein Buch schreiben würdest, wovon würde es handeln?", category: "Träume & Zukunft" },
  { text: "Welchen kleinen Luxus wünschst du dir im Alltag, erlaubst ihn dir aber nicht?", category: "Träume & Zukunft" },
  { text: "Wovon würdest du dir mehr wünschen, ohne dass es materiell wäre?", category: "Träume & Zukunft" },
  { text: "Welche Version deiner selbst möchtest du in 10 Jahren sehen?", category: "Träume & Zukunft" },
  { text: "Gibt es einen Traum, den du noch nie laut ausgesprochen hast?", category: "Träume & Zukunft" },
  { text: "Was hält dich davon ab, das zu machen, wovon du träumst?", category: "Träume & Zukunft" },
  { text: "Welche Reise willst du unbedingt noch machen — und was würde sie verändern?", category: "Träume & Zukunft" },
  { text: "Wenn du einen Tag lang eine andere Person sein könntest — wer wäre es?", category: "Träume & Zukunft" },
  { text: "Welchen Ort würdest du ungern sterben — welchen gern?", category: "Träume & Zukunft" },

  // ---------- Kindheit & Wurzeln (15) ----------
  { text: "Hattest du eine schöne Kindheit?", category: "Kindheit & Wurzeln" },
  { text: "Für welche Dinge hast du dich schon als Kind begeistert und hast dir diese Begeisterung bis heute beibehalten?", category: "Kindheit & Wurzeln" },
  { text: "Was war der größte Mist, den du als Jugendlicher gebaut hast?", category: "Kindheit & Wurzeln" },
  { text: "Welche Geschichte aus deiner Jugend wirst du deinen Kindern und Enkeln am häufigsten erzählen?", category: "Kindheit & Wurzeln" },
  { text: "Welcher Geruch bringt dich sofort in deine Kindheit zurück?", category: "Kindheit & Wurzeln" },
  { text: "Wer war dein bester Freund als Kind — und wisst ihr noch voneinander?", category: "Kindheit & Wurzeln" },
  { text: "Welche Geschichte wird in deiner Familie immer wieder erzählt?", category: "Kindheit & Wurzeln" },
  { text: "Was hättest du als Kind gebraucht, das du nicht bekommen hast?", category: "Kindheit & Wurzeln" },
  { text: "Welchen Beruf wolltest du werden, bevor du wusstest, was ein Beruf ist?", category: "Kindheit & Wurzeln" },
  { text: "Gibt es einen Ort aus deiner Kindheit, an den du nie mehr zurück möchtest?", category: "Kindheit & Wurzeln" },
  { text: "Was ist deine früheste Erinnerung?", category: "Kindheit & Wurzeln" },
  { text: "Welches Spielzeug hast du vermisst, als du älter wurdest?", category: "Kindheit & Wurzeln" },
  { text: "Wer in deiner Familie versteht dich am wenigsten — und wer am meisten?", category: "Kindheit & Wurzeln" },
  { text: "Was hat deine Eltern geprägt, das sich bei dir fortgesetzt hat?", category: "Kindheit & Wurzeln" },
  { text: "Worauf warst du als Kind besonders stolz?", category: "Kindheit & Wurzeln" },

  // ---------- Herzensmenschen (20) ----------
  { text: "Wer war für dich die einflussreichste Person in deinem Leben?", category: "Herzensmenschen" },
  { text: "Wann und mit welcher Person hattest du deinen größten Streit? Wie ist es ausgegangen?", category: "Herzensmenschen" },
  { text: "Welche aktuell lebende Person würdest du am liebsten treffen — und warum?", category: "Herzensmenschen" },
  { text: "Wenn du eine berühmte Persönlichkeit — egal ob lebendig oder tot — treffen dürftest: wer wäre es und warum?", category: "Herzensmenschen" },
  { text: "Was glaubst du haben wir gemeinsam?", category: "Herzensmenschen" },
  { text: "Wer in deinem Leben weiß etwas, das niemand anderes weiß?", category: "Herzensmenschen" },
  { text: "Wem schuldest du eine Entschuldigung, die du nie ausgesprochen hast?", category: "Herzensmenschen" },
  { text: "Wen vermisst du, ohne es zu sagen?", category: "Herzensmenschen" },
  { text: "Welche Freundschaft hat dich am meisten verändert?", category: "Herzensmenschen" },
  { text: "Wer hat dir zuletzt etwas gesagt, das du nicht vergessen konntest?", category: "Herzensmenschen" },
  { text: "Wem würdest du schreiben, wenn du wüsstest, du stirbst morgen?", category: "Herzensmenschen" },
  { text: "Welche Person in deinem Leben ist am schwersten zu erreichen — emotional?", category: "Herzensmenschen" },
  { text: "Wen hast du in deinem Leben unterschätzt?", category: "Herzensmenschen" },
  { text: "Welche Person hat dich am meisten liebgehabt — und weißt du, ob sie es wusste?", category: "Herzensmenschen" },
  { text: "Wer hat dir zum letzten Mal „Ich habe dich lieb“ gesagt?", category: "Herzensmenschen" },
  { text: "Mit welchem Menschen fühlst du dich ohne Worte verstanden?", category: "Herzensmenschen" },
  { text: "Wem gegenüber hast du dich am meisten verstellt — und warum?", category: "Herzensmenschen" },
  { text: "Welches Verhalten anderer trifft dich am härtesten?", category: "Herzensmenschen" },
  { text: "Wen beneidest du heimlich — und wofür?", category: "Herzensmenschen" },
  { text: "Mit wem würdest du gern noch einmal sprechen?", category: "Herzensmenschen" },
  { text: "Warst du schon mal emotional abhängig von einem Menschen?", category: "Herzensmenschen" },
  { text: "Hast du schon mal jemanden gebraucht — und gespürt, dass das ungesund war?", category: "Herzensmenschen" },
  { text: "Gibt es einen Menschen, ohne den du dir dein Leben damals nicht vorstellen konntest, und der heute nicht mehr da ist?", category: "Herzensmenschen" },
  { text: "Wann hast du zuletzt jemanden festgehalten, obwohl ein Teil von dir wusste, dass es nicht mehr trug?", category: "Herzensmenschen" },
  { text: "Hast du schon mal aus Angst vor dem Allein-Sein bei jemandem gewartet, der nicht zurückkam?", category: "Herzensmenschen" },
  { text: "Gibt es einen Menschen, dessen Stimmung deinen ganzen Tag färbt — und wann ist dir das zum ersten Mal aufgefallen?", category: "Herzensmenschen" },
  { text: "Was war die längste Zeit, in der du jemanden täglich vermisst hast — und wie hast du das ausgehalten?", category: "Herzensmenschen" },
  { text: "Wann hast du dich von einer emotionalen Abhängigkeit gelöst — und woran hast du gemerkt, dass es Zeit war?", category: "Herzensmenschen" },
  { text: "Wer hat dich zum ersten Mal so geliebt, dass du gemerkt hast, wie wenig du es vorher kanntest?", category: "Herzensmenschen" },
  { text: "Was war der erste Mensch, dessen Tod oder Verlust dir wirklich klar gemacht hat, dass Liebe und Zeit endlich sind?", category: "Herzensmenschen" },

  // ---------- Arbeit & Berufung (20) ----------
  { text: "Wann warst du zuletzt in deiner Arbeit so vertieft, dass du die Zeit vergessen hast — was hast du da gemacht?", category: "Arbeit & Berufung" },
  { text: "Welche Tätigkeit würdest du machen, auch wenn niemand dich dafür bezahlen würde?", category: "Arbeit & Berufung" },
  { text: "Wann hast du in deinem Job zuletzt einen echten Moment von Sinn gespürt — und wann das letzte Mal von Leere?", category: "Arbeit & Berufung" },
  { text: "Was frisst Energie in deiner Woche, ohne dass es einen klaren Output hat?", category: "Arbeit & Berufung" },
  { text: "Wenn dein heutiges Ich mit 22 wäre — würde es deinen jetzigen Job wählen?", category: "Arbeit & Berufung" },
  { text: "Welcher Beruf von Freund:innen oder Bekannten fasziniert dich heimlich?", category: "Arbeit & Berufung" },
  { text: "Was ist die ehrlichste Antwort auf die Frage „Warum machst du diesen Job?“ — jenseits von Geld?", category: "Arbeit & Berufung" },
  { text: "Wenn du in 20 Jahren auf dein Berufsleben zurückblickst — woran wirst du es messen?", category: "Arbeit & Berufung" },
  { text: "Was machst du heute, was dich in 10 Jahren wahrscheinlich nicht mehr ausfüllt?", category: "Arbeit & Berufung" },
  { text: "Wann warst du zuletzt in deiner Arbeit so vertieft, dass du die Zeit vergessen hast?", category: "Arbeit & Berufung" },
  { text: "Was würdest du tun, wenn Geld keine Rolle spielte — und was, wenn Status keine Rolle spielte?", category: "Arbeit & Berufung" },
  { text: "Was ist die ehrlichste Antwort auf die Frage „Warum machst du diesen Job?“?", category: "Arbeit & Berufung" },
  { text: "Wenn du in 20 Jahren zurückblickst — woran wirst du dein Berufsleben messen?", category: "Arbeit & Berufung" },
  { text: "Wofür arbeitest du eigentlich?", category: "Arbeit & Berufung" },
  { text: "Wann hast du zuletzt bei der Arbeit gedacht: „Dafür bin ich hier“?", category: "Arbeit & Berufung" },
  { text: "Welchen Teil deiner Arbeit hasst du — und warum machst du ihn trotzdem?", category: "Arbeit & Berufung" },
  { text: "Wie viel deines Selbstwerts hängt an dem, was du beruflich tust?", category: "Arbeit & Berufung" },
  { text: "Wenn du morgen gekündigt würdest — wäre es auch eine Erleichterung?", category: "Arbeit & Berufung" },
  { text: "Welches berufliche Kompliment war dir wirklich wichtig?", category: "Arbeit & Berufung" },
  { text: "Was würdest du deiner Arbeit in fünf Worten sagen?", category: "Arbeit & Berufung" },

  // ---------- Tiefgang (25) ----------
  { text: "Worüber denkst du abends manchmal nach, was du tagsüber verdrängst?", category: "Tiefgang" },
  { text: "Was würdest du sagen, wenn niemand zuhörte — und du wüsstest, dass es keine Folgen hat?", category: "Tiefgang" },
  { text: "Welche Frage hast du Angst, dir selbst zu stellen?", category: "Tiefgang" },
  { text: "Was ist eine Sorge, die du mit anderen nicht teilst — und warum nicht?", category: "Tiefgang" },
  { text: "Wovor hast du heimlich Angst, was die meisten Menschen wahrscheinlich nicht ahnen?", category: "Tiefgang" },
  { text: "Was wäre, wenn deine größte Angst tatsächlich einträte — wie würde dein Leben aussehen?", category: "Tiefgang" },
  { text: "Was hast du noch nie jemandem erzählt, was eigentlich Erzählens wert wäre?", category: "Tiefgang" },
  { text: "Welches Gefühl trägst du oft mit dir, ohne es zu benennen?", category: "Tiefgang" },
  { text: "Welche Beziehung in deinem Leben fühlt sich gerade nicht gut an, und du sprichst nicht darüber?", category: "Tiefgang" },
  { text: "Welcher Satz, den jemand mal zu dir gesagt hat, trägt dich noch heute?", category: "Tiefgang" },
  { text: "Welche Person würde es merken, wenn du plötzlich nicht mehr da wärst — und merkst du es bei ihr?", category: "Tiefgang" },
  { text: "Worüber denkst du abends nach, was du tagsüber verdrängst?", category: "Tiefgang" },
  { text: "Welche kleine tägliche Handlung hält dich stabil?", category: "Tiefgang" },
  { text: "Für welches Ereignis deines Lebens bist du am dankbarsten?", category: "Tiefgang" },
  { text: "Für welche drei Dinge in deinem Leben bist du am dankbarsten?", category: "Tiefgang" },
  { text: "Gibt es eine Erfahrung, die dein Leben nachhaltig verändert hat?", category: "Tiefgang" },
  { text: "Welches ist das beste Buch, das du gelesen hast?", category: "Tiefgang" },
  { text: "Wenn du ein Video haben könntest von einer Situation deiner Wahl aus deinem Leben — welche Situation wäre das?", category: "Tiefgang" },
  { text: "Was weißt du über dich, das du anderen nicht sagen könntest?", category: "Tiefgang" },
  { text: "Wann hast du zuletzt geweint — und was war der wirkliche Grund?", category: "Tiefgang" },
  { text: "Welche innere Stimme begleitet dich am meisten — und wie klingt sie?", category: "Tiefgang" },
  { text: "Was bereust du am meisten — und hast du dir selbst vergeben?", category: "Tiefgang" },
  { text: "Gibt es einen Moment, in dem du jemanden nicht losgelassen hast, obwohl er hätte gehen dürfen?", category: "Tiefgang" },
  { text: "Was würdest du sagen, wenn niemand antworten müsste?", category: "Tiefgang" },
  { text: "Was bedeutet Versöhnung für dich — mit dir selbst?", category: "Tiefgang" },

  // ---------- Leicht & Humor (22) ----------
  { text: "Welche historische Figur würde im Gruppenchat ständig auf „Nachricht gelesen“ machen — und warum gerade die?", category: "Leicht & Humor" },
  { text: "Bei einer Zombie-Apokalypse: Welches völlig unnütze Hobby würde dich überleben lassen?", category: "Leicht & Humor" },
  { text: "Welche zwei Promis würdest du zu einer Dinner-Party einladen, damit sie sich streiten?", category: "Leicht & Humor" },
  { text: "Würdest du lieber ein Jahr lang nur durch GIFs kommunizieren — oder jeden Satz mit einer Lüge beginnen?", category: "Leicht & Humor" },
  { text: "Dein Kühlschrank reproduziert mysteriös eine Zutat unbegrenzt — welche soll es sein und warum?", category: "Leicht & Humor" },
  { text: "Würdest du lieber wissen, wann du stirbst — oder wie?", category: "Leicht & Humor" },
  { text: "Welcher Film müsste neu verfilmt werden — aber als TikTok-Tanzchallenge?", category: "Leicht & Humor" },
  { text: "Welche Sportart sollte mit völlig falschen Regeln olympisch werden?", category: "Leicht & Humor" },
  { text: "Welcher Instagram-Filter beschreibt deine Persönlichkeit am besten — nicht dein Aussehen?", category: "Leicht & Humor" },
  { text: "Welche App sollte dringend eine „Das war Sarkasmus!“-Autokorrektur einführen?", category: "Leicht & Humor" },
  { text: "Welche völlig sinnlose Fähigkeit hast du in den letzten Jahren perfektioniert?", category: "Leicht & Humor" },
  { text: "Welcher Wikipedia-Artikel sollte gelöscht werden, um maximales Chaos zu verursachen?", category: "Leicht & Humor" },
  { text: "Welche historische Figur würde im Gruppenchat ständig auf „Nachricht gelesen“ machen?", category: "Leicht & Humor" },
  { text: "Du erbst ein Schloss — was machst du damit?", category: "Leicht & Humor" },
  { text: "Dein Kühlschrank reproduziert eine Zutat unbegrenzt — welche?", category: "Leicht & Humor" },
  { text: "Welcher Instagram-Filter beschreibt deine Persönlichkeit am besten?", category: "Leicht & Humor" },
  { text: "Welcher Film müsste als TikTok-Tanzchallenge neu verfilmt werden?", category: "Leicht & Humor" },
  { text: "Welche peinlichste Automatikreaktion passiert dir immer wieder?", category: "Leicht & Humor" },
  { text: "Welche Popsong-Zeile singst du in deinem Kopf, wenn niemand zuschaut?", category: "Leicht & Humor" },
  { text: "Welches Gericht würdest du essen, wenn Kalorien nicht zählen würden — eine Woche lang?", category: "Leicht & Humor" },
  { text: "Welche drei Alltagsentscheidungen brauchst du am längsten zu treffen?", category: "Leicht & Humor" },
  { text: "Welches Kleidungsstück aus deiner Jugend bereust du heute am meisten?", category: "Leicht & Humor" },

  // ---------- Absurd & Erlebt (12) ----------
  { text: "Was war das schlimmste Date, das du je hattest?", category: "Absurd & Erlebt" },
  { text: "Was ist das Peinlichste, das dir je beim Feiern passiert ist?", category: "Absurd & Erlebt" },
  { text: "Was ist das Lustigste, das du beim Feiern erlebt hast?", category: "Absurd & Erlebt" },
  { text: "Was war das größte Missverständnis, das dir je passiert ist?", category: "Absurd & Erlebt" },
  { text: "Was war das seltsamste Geschenk, das du je bekommen hast?", category: "Absurd & Erlebt" },
  { text: "Welche Prüfung oder welches Vorstellungsgespräch ist am schiefsten gelaufen?", category: "Absurd & Erlebt" },
  { text: "Was war das Unangenehmste, was du zufällig mitgehört hast?", category: "Absurd & Erlebt" },
  { text: "Gab es einen Moment, in dem du dachtest, du stirbst gleich?", category: "Absurd & Erlebt" },
  { text: "In welcher Situation warst du so fremd, dass es schon wieder lustig war?", category: "Absurd & Erlebt" },
  { text: "Welche Handwerker- oder Restaurant-Geschichte erzählst du am häufigsten?", category: "Absurd & Erlebt" },
  { text: "Was hat dich zuletzt so zum Lachen gebracht, dass du kurz Angst um deine Atmung hattest?", category: "Absurd & Erlebt" },
  { text: "Was war das Peinlichste, das dir in einer öffentlichen Situation passiert ist?", category: "Absurd & Erlebt" },

  // ---------- Bunt gemischt (38) ----------
  { text: "Was ist eine kleine Sache im Alltag, die dich unverhältnismäßig glücklich macht?", category: "Bunt gemischt" },
  { text: "Was hast du zuletzt zum allerersten Mal in deinem Leben gemacht?", category: "Bunt gemischt" },
  { text: "Welche kleine Sache lässt dich sofort nostalgisch werden?", category: "Bunt gemischt" },
  { text: "Gibt es etwas, das andere Leute oft an dir falsch einschätzen?", category: "Bunt gemischt" },
  { text: "Was hat dich zuletzt zum Staunen gebracht?", category: "Bunt gemischt" },
  { text: "Wenn dein Leben gerade ein Buch wäre — welchen Titel hätte es?", category: "Bunt gemischt" },
  { text: "Welches „unsichtbare Tattoo“ trägst du — also welche Erfahrung prägt dich, obwohl man es dir nicht ansieht?", category: "Bunt gemischt" },
  { text: "Angenommen, du könntest einen Tag mit deinem 15-jährigen Ich verbringen — was würdet ihr besprechen?", category: "Bunt gemischt" },
  { text: "In welcher Version deiner selbst fühlst du dich am wohlsten — und wann warst du zuletzt dort?", category: "Bunt gemischt" },
  { text: "Welche Eigenschaft an dir möchtest du unbedingt behalten, selbst wenn du mal 100 Jahre alt bist?", category: "Bunt gemischt" },
  { text: "Wen in deinem Leben würdest du gerne wieder anrufen, hast es aber zu lange nicht getan?", category: "Bunt gemischt" },
  { text: "Welche Eigenschaft deiner Eltern siehst du heute mit mehr Verständnis als früher?", category: "Bunt gemischt" },
  { text: "Was hast du jemandem zuletzt gesagt, was du schon länger hättest sagen sollen?", category: "Bunt gemischt" },
  { text: "Wem würdest du gerne noch einmal danken können — und wofür?", category: "Bunt gemischt" },
  { text: "Wenn du eine Sache an der Gesellschaft sofort ändern könntest — welche wäre das und warum?", category: "Bunt gemischt" },
  { text: "Welche Frage würdest du gerne mit „Ja“ beantworten können, kannst es aber (noch) nicht?", category: "Bunt gemischt" },
  { text: "Gibt es eine Erfahrung, die sich erst wie ein Misserfolg angefühlt hat, sich aber als wertvolle Lektion entpuppte?", category: "Bunt gemischt" },
  { text: "Welche kleine Entscheidung in deinem Leben hat überraschend große Auswirkungen gehabt?", category: "Bunt gemischt" },
  { text: "Welche Rolle spielst du unbewusst in Gruppen — und passt sie noch zu dir?", category: "Bunt gemischt" },
  { text: "Was nimmst du dir jedes Jahr vor, machst es aber nicht — und warum wahrscheinlich?", category: "Bunt gemischt" },
  { text: "Welcher Tag aus den letzten 12 Monaten war für dich besonders — und woran hast du das gemerkt?", category: "Bunt gemischt" },
  { text: "Wenn du wüsstest, dass dir genau ein Jahr bleibt — was würde sich sofort ändern, und was nicht?", category: "Bunt gemischt" },
  { text: "Was ist eine kleine tägliche Handlung, die dich stabil hält?", category: "Bunt gemischt" },
  { text: "Was würdest du gerne ausprobieren, hast dich aber bisher nie getraut?", category: "Bunt gemischt" },
  { text: "Angenommen, du hättest ab morgen ein Jahr frei von allen Verpflichtungen und genug Geld — wie würdest du es verbringen?", category: "Bunt gemischt" },
  { text: "Was ist deine „andere Karriere“ — das Leben, das du auch hättest führen können?", category: "Bunt gemischt" },
  { text: "Wenn dein Leben als Netflix-Serie erscheinen würde — welches Genre wäre es, und wie hieße die aktuelle Staffel?", category: "Bunt gemischt" },
  { text: "Welcher Satz, den jemand mal zu dir gesagt hat, ist geblieben?", category: "Bunt gemischt" },
  { text: "Welche kleine Geste von jemand anderem kann dich sofort für diese Person einnehmen?", category: "Bunt gemischt" },
  { text: "Welches „unsichtbare Tattoo“ trägst du — was prägt dich, obwohl man es dir nicht ansieht?", category: "Bunt gemischt" },
  { text: "Welche Erfahrung hat sich erst wie ein Misserfolg angefühlt — und war später eine wertvolle Lektion?", category: "Bunt gemischt" },
  { text: "Welche Person aus deinem Leben hat dich mehr geprägt, als sie selbst weiß?", category: "Bunt gemischt" },
  { text: "In welcher Beziehung spürst du gerade, dass Aufmerksamkeit fehlt?", category: "Bunt gemischt" },
  { text: "Wenn du wüsstest, dass dir genau ein Jahr bleibt — was würde sich sofort ändern, was nicht?", category: "Bunt gemischt" },
  { text: "Was würdest du gerne ausprobieren, hast dich aber nie getraut?", category: "Bunt gemischt" },
  { text: "Wenn du ein Jahr frei hättest und genug Geld — wie würdest du es verbringen?", category: "Bunt gemischt" },
  { text: "Angenommen, dein zukünftiges Ich schreibt dir einen Brief — was würde darin stehen?", category: "Bunt gemischt" },
  { text: "Was ist eine Sache, von der alle Leute begeistert scheinen und du kannst einfach nicht nachvollziehen wieso?", category: "Bunt gemischt" },

  // ---------- Ü18 · Spicy (22) ----------
  { text: "Was findest du sexy, was andere vielleicht nicht verstehen würden?", category: "Ü18 · Spicy" },
  { text: "Gibt es eine Fantasie, die du dich nie getraut hast auszusprechen?", category: "Ü18 · Spicy" },
  { text: "Welcher Moment mit einem Menschen war für dich der intimste — und warum?", category: "Ü18 · Spicy" },
  { text: "Welche Grenze hast du in Beziehungen neu verhandelt, weil sie nicht mehr gestimmt hat?", category: "Ü18 · Spicy" },
  { text: "Welches Tabu hast du heimlich spannend gefunden, ohne es laut auszusprechen?", category: "Ü18 · Spicy" },
  { text: "Was war der mutigste Moment in deinem Sexleben?", category: "Ü18 · Spicy" },
  { text: "Wann hast du dich zuletzt richtig begehrt gefühlt?", category: "Ü18 · Spicy" },
  { text: "Welches Thema rund um Sex fällt dir am schwersten anzusprechen?", category: "Ü18 · Spicy" },
  { text: "Welche Rolle spielt Sex in deinem Leben — verglichen mit vor fünf Jahren?", category: "Ü18 · Spicy" },
  { text: "Was macht dich im Bett unsicher?", category: "Ü18 · Spicy" },
  { text: "Gibt es etwas, wovon du weißt, dass es dich erregt, du dich aber scheust, es zuzugeben?", category: "Ü18 · Spicy" },
  { text: "Wie ehrlich bist du mit dir selbst in deinen erotischen Wünschen?", category: "Ü18 · Spicy" },
  { text: "Wann hattest du zuletzt richtig guten Sex — und was war anders als sonst?", category: "Ü18 · Spicy" },
  { text: "Welche Eigenschaft macht einen Menschen für dich sofort anziehend — jenseits vom Aussehen?", category: "Ü18 · Spicy" },
  { text: "Was war das Intimste, das du je jemandem geschrieben hast?", category: "Ü18 · Spicy" },
  { text: "Gibt es ein „Erstes Mal“, das noch kommen soll?", category: "Ü18 · Spicy" },
  { text: "Was fehlt dir in deinem Intimleben, ohne dass du es ansprichst?", category: "Ü18 · Spicy" },
  { text: "Welches Lied bringt dich sofort in eine bestimmte erotische Erinnerung zurück?", category: "Ü18 · Spicy" },
  { text: "Wie willst du gerade jetzt berührt werden?", category: "Ü18 · Spicy" },
  { text: "Was war das Riskanteste, was du je im Intimen getan hast?", category: "Ü18 · Spicy" },
  { text: "Wovon träumst du nachts, worüber du tagsüber nicht sprichst?", category: "Ü18 · Spicy" },
  { text: "Was wäre in deinem Intimleben heute möglich, wenn du weniger Scham hättest?", category: "Ü18 · Spicy" },

];

window.QUESTION_CATEGORIES = [...new Set(window.QUESTIONS.map(q => q.category))];
